/* ===============================================================================

	---------------------------------
	-*- [CS] Max Speed: Constants -*-
	---------------------------------

	- Discord Server: https://discord.gg/S6Cj3Wn
	- Website:
		* https://rvrealm.com
		* https://community.rvrealm.com/forums/forumdisplay.php?fid=19

=============================================================================== */

//
// Counter-Strike Max Speed Functions
//

#if defined _cs_maxspeed_api_const_inc
	#endinput
#endif
#define _cs_maxspeed_api_const_inc

/**
 * Maxspeed barriers
 */
#define CS_MAXSPEED_BARRIER_MIN 0.0
#define CS_MAXSPEED_BARRIER_MAX 10.0

/**
 * Knife maxspeed in CS
 */
#define CS_KNIFE_MAXSPEED 250.0