/* ===============================================================================

	----------------------------
	-*- [ZP] Core: Constants -*-
	----------------------------

	- Discord Server: https://discord.gg/S6Cj3Wn
	- Website:
		* https://rvrealm.com
		* https://community.rvrealm.com/forums/forumdisplay.php?fid=19

=============================================================================== */

//
// Zombie Plague Functions
//

#if defined _zp_core_const_inc
	#endinput
#endif
#define _zp_core_const_inc

/**
 * Version string and number
 */
#define ZP_VERSION_STR "1.1.0"
#define ZP_VERSION_NUM 110

/**
 * Author
 */
#define ZP_AUTHOR "RV: ZP Dev Team"

/**
 * Message prefixes
 */
#define ZP_PREFIX "[ZP]"
#define ZP_PREFIX_COLOR "^4[ZP]^1"

/**
 * Out of range integer and float values
 */
#define ZP_OUT_OF_RANGE -1
#define ZP_OUT_OF_RANGE_FLOAT -1.0

/**
 * Menu return values
 */
#define ZP_MENU_ITEM_AVAILABLE 0
#define ZP_MENU_ITEM_UNAVAILABLE 1
#define ZP_MENU_ITEM_DO_NOT_SHOW 2
